import { Language, Translation } from './types';
import { LayoutDashboard, GitGraph, Settings, Zap } from 'lucide-react';
import React from 'react';

export const TRANSLATIONS: Record<Language, Translation> = {
  [Language.ENGLISH]: {
    dashboard: 'Dashboard',
    flowEditor: 'Flow Editor',
    settings: 'Settings',
    welcome: 'Welcome back, User',
    totalFlows: 'Total Flows',
    activeUsers: 'Active Users',
    successRate: 'Success Rate',
    recentActivity: 'Recent Activity',
    createFlow: 'Create Flow',
    aiAssistant: 'AI Assistant',
    askAi: 'Ask Gemini about your flows...',
    typing: 'Gemini is thinking...',
    language: 'Language',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    genFlow: 'Generate Flow',
    flowName: 'Project Alpha',
    nodes: 'Nodes',
    edges: 'Edges',
    execute: 'Execute',
    connectWallet: 'Connect',
    logout: 'Logout',
    search: 'Search...',
  },
  [Language.ARABIC]: {
    dashboard: 'لوحة القيادة',
    flowEditor: 'محرر التدفق',
    settings: 'الإعدادات',
    welcome: 'مرحبًا بك مجددًا',
    totalFlows: 'إجمالي التدفقات',
    activeUsers: 'المستخدمون النشطون',
    successRate: 'معدل النجاح',
    recentActivity: 'النشاط الأخير',
    createFlow: 'إنشاء تدفق',
    aiAssistant: 'مساعد الذكاء الاصطناعي',
    askAi: 'اسأل جيمناي عن تدفقاتك...',
    typing: 'جيمناي يفكر...',
    language: 'اللغة',
    theme: 'السمة',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    genFlow: 'توليد تدفق',
    flowName: 'المشروع ألفا',
    nodes: 'العقد',
    edges: 'الروابط',
    execute: 'تنفيذ',
    connectWallet: 'اتصال',
    logout: 'تسجيل الخروج',
    search: 'بحث...',
  },
  [Language.SORANI]: {
    dashboard: 'داشبۆرد',
    flowEditor: 'دەستکاری کردنی لێشاو',
    settings: 'ڕێکخستنەکان',
    welcome: 'بەخێربێیتەوە',
    totalFlows: 'کۆی لێشاوەکان',
    activeUsers: 'بەکارهێنەرانی چالاک',
    successRate: 'ڕێژەی سەرکەوتن',
    recentActivity: 'چالاکیەکانی دوایی',
    createFlow: 'دروستکردنی لێشاو',
    aiAssistant: 'یاریدەدەری زیرەک',
    askAi: 'پرسیار لە جێمینای بکە...',
    typing: 'جێمینای بیر دەکاتەوە...',
    language: 'زمان',
    theme: 'ڕووکار',
    darkMode: 'دۆخی تاریک',
    lightMode: 'دۆخی ڕووناک',
    genFlow: 'بەرهەمهێنانی لێشاو',
    flowName: 'پرۆژەی ئەلفا',
    nodes: 'گرێکان',
    edges: 'لێوارەکان',
    execute: 'جێبەجێکردن',
    connectWallet: 'پەیوەستکردن',
    logout: 'دەرچوون',
    search: 'گەڕان...',
  },
  [Language.BADINI]: {
    dashboard: 'داشبۆرد',
    flowEditor: 'دەستکاری کرنی لێشاوی',
    settings: 'سەبتاندن',
    welcome: 'ب خێر هاتی',
    totalFlows: 'هەمی لێشاو',
    activeUsers: 'بەکارهێنەرێن چالاک',
    successRate: 'رێژا سەرکەفتنێ',
    recentActivity: 'چالاکیێن نوی',
    createFlow: 'لێشاوێ دروست بکە',
    aiAssistant: 'هاریکارێ ژیر',
    askAi: 'پرسیار ژ جێمینای بکە...',
    typing: 'جێمینای یێ هزر دکەت...',
    language: 'زمان',
    theme: 'رووکار',
    darkMode: 'مۆدێ تاری',
    lightMode: 'مۆدێ روون',
    genFlow: 'بەرهەمهینانا لێشاوی',
    flowName: 'پرۆژێ ئەلفا',
    nodes: 'گرێک',
    edges: 'لێوار',
    execute: 'بجهئینان',
    connectWallet: 'گرێدان',
    logout: 'دەرکەفتن',
    search: 'لێگەریان...',
  },
};

export const MOCK_CHART_DATA = [
  { name: 'Jan', flows: 40, errors: 24, amt: 2400 },
  { name: 'Feb', flows: 30, errors: 13, amt: 2210 },
  { name: 'Mar', flows: 20, errors: 58, amt: 2290 },
  { name: 'Apr', flows: 27, errors: 39, amt: 2000 },
  { name: 'May', flows: 18, errors: 48, amt: 2181 },
  { name: 'Jun', flows: 23, errors: 38, amt: 2500 },
  { name: 'Jul', flows: 34, errors: 43, amt: 2100 },
];
